[package]
name = "absinthe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
absinthe_macros = { path = "./absinthe_macros" }

[dev-dependencies]
lazy_static = "1"